app:
  redis:
    enabled: true
    conn: redis:6379
    dbNum: 8
    password:
    timeout: 3000
    sentinel:
      enabled: false
      master: bookMaster
      nodes: redis:16379,redis:26379,redis:36379
